setting:
  output_path: ./media/     # 输出路径
  l_threads: 3              # list_files线程数
  p_threads: 8              # processing_file线程数
  subtitle: True            # 是否下载字幕
  img: True                # 是否下载图片
  nfo: True                 # 是否下载视频信息文件
webdav:
  动漫:                                        # 任意字符，用于标识Webdav服务器
    url: https://al.chirmyram.com/dav/ani/    # Webdav服务器URL
    username: alist                             # Webdav账号
    password: alist                             # Webdav密码