setting:
  output_path: ./media/     # 输出路径
  l_threads: 20              # list_files线程数
  subtitle: True            # 是否下载字幕
  img: True                # 是否下载图片
  nfo: True                 # 是否下载视频信息文件
  url_encode: True          # 是否对生成的strm文件中的链接进行URL编码
webdav:
  动漫A:                                        # 任意字符，用于标识Webdav服务器
    url: https://al.chirmyram.com/dav/ani/   # Webdav服务器URL
    username: alist                             # Webdav账号
    password: alist                             # Webdav密码
    token:

